version: '3.8'

services:
  web:
    container_name: fast_api
    image: fast_api_dev
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      PYTHONNUNBUFFERED: 1
      WAIT_HOSTS: "postgres_db:5432"
      WAIT_HOSTS_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 2
      WAIT_HOST_CONNECT_TIMEOUT: 30
    depends_on:
      - db
## Use dummy user and password for now, configure 
      #user and password environment later
  db:
    image: postgres:16
    restart: always
    container_name: postgres_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-employers
    ports:
      - 5432:5432

volumes:
    postgres_data:
