name: Run Tests on Main Branch Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get install -y docker-compose

    - name: Build and run Docker containers
      run: |
        docker-compose up -d
        docker ps

    - name: Run pytest
      run: |
        docker exec -i fast_api pytest tests/service/stats.py

    - name: Stop Docker containers
      run: |
        docker-compose down
      if: always() 
